POST  http://localhost:8080/api/register HTTP/1.1
content-type: application/json

{
    "id": 1,
    "firstname": "test",
    "lastname": "test",
    "personNumber": "test",
    "email": "test",
    "password": "mytest",
    "role": 1,
    "username": "testuser"
}

###

POST  http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
    "username": "testuser",
    "password": "mytest"

}

