name: build and deploy
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: feature-login
      - name: setup_java
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          java-package: 'jdk'
          distribution: 'temurin'
      - name: setup_node
        uses: actions/setup-node@v4.2.0
      - name: setup_db
        env:
          PGPASSWORD: postgres
        run: |
          sudo apt-get install -y postgresql-client
          psql -U postgres -h localhost -d postgres -f $GITHUB_WORKSPACE/existing-database.sql
          
      - name: build 
        if: ${{success()}}
        env: 
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          SPRING_PORT: 8080
        run: |
          
          cd $GITHUB_WORKSPACE
          cd recruitment-frontend/
          npm ci
          npm run build
          cp -r build/. ../recruitment-backend/src/main/resources/public
          cd ../recruitment-backend/
          ./mvnw package

          

      - name: save_build
        uses: actions/upload-artifact@v4.6.0
        with:
          name: saved_build
          path: recruitment-backend/target/*.jar
  deploy:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: feature-login
      - name: get_build
        uses: actions/download-artifact@v4.1.8
        with:
          Name: saved_build
          path: recruitment-backend/target/
      - name: setup_docker 
        uses: docker/setup-docker-action@v4.1.0
      - name: setup_heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh     

      - name: deploy
        if: ${{success()}}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API }}
        run: |
          cd $GITHUB_WORKSPACE
          docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
          docker buildx build --provenance false --platform linux/amd64 -t registry.heroku.com/iv1201-recr/web .
          docker push registry.heroku.com/iv1201-recr/web 
          heroku container:release web --app=iv1201-recr 
          
        
        
        
